---
title: "Assignment 2 - ST462"
author: "Carson Boettinger"
date: "`r Sys.Date()`"
output: html_document
---
Importing Libaries that I use
```{r load_packages1, message = FALSE}
if (!require(gridExtra)) install.packages('gridExtra', dependencies = TRUE) 
library(gridExtra)
if (!require(knitr)) install.packages('knitr', dependencies = TRUE) 
library(knitr)
if (!require(GGally)) install.packages('GGally', dependencies = TRUE)
library(GGally)
if (!require(kableExtra)) install.packages('kableExtra', dependencies = TRUE) 
library(kableExtra)
if (!require(jtools)) install.packages('jtools', dependencies = TRUE) 
library(jtools)
if (!require(rsample)) install.packages('rsample', dependencies = TRUE)
library(rsample)
if (!require(broom)) install.packages('broom', dependencies = TRUE) 
library(broom)
if (!require(tidyverse)) install.packages('tidyverse', dependencies = TRUE)
library(tidyverse)
```
```{r include=FALSE}
if(knitr::is_html_output()){options(knitr.table.format = "html")} else {options(knitr.table.format = "latex")}
```

Question 2
Question a
```{r}
cases=c(1,6,16,23,27,39,31,30,43,51,63,70,88,97,91,104,110,113,149,159)
time_period=1:20
plot(cases~time_period,xlab="Time Period",ylab="Cases",pch=20)
```
Question B
```{r}
cases=c(1,6,16,23,27,39,31,30,43,51,63,70,88,97,91,104,110,113,149,159)
time_period=1:20
plot(log(cases)~log(time_period),xlab="log(i)",ylab="log(yi)",pch=20)
```

Question C
```{r}
cases=c(1,6,16,23,27,39,31,30,43,51,63,70,88,97,91,104,110,113,149,159)
time_period=1:20

question2c <- glm(formula = cases~time_period,family = "poisson")

summary(question2c)
```



Question 3
```{r}
install.packages("MASS")
library(MASS)
```
```{r}
data(Insurance)
```

```{r}
Insurance <- Insurance %>%
  mutate(Age = case_when(
    Age == "<25" ~ 1,
    Age == "25-29" ~ 2,
    Age == "30-35" ~ 3,
    Age == ">35" ~ 4
  ))
```

```{r}
Insurance <- Insurance %>%
  mutate(Group = case_when(
    Group == "<1l" ~ 1,
    Group == "1-1.5l" ~ 2,
    Group == "1.5-2l" ~ 3,
    Group == ">2l" ~ 4
  ))
```


```{r}
model_a <- glm(Claims ~ Age,data = Insurance, family = poisson)
summary(model_a)
```
```{r}
neg_model <- glm.nb(Claims ~ Age + offset(log(Holders)), data = Insurance)
summary(neg_model)
```


Question B
```{r}
# Estimated coefficients
beta_hat <- coef(neg_model)
cat("Estimated coefficients (beta hat):\n")
print(beta_hat)
```

```{r}
# Estimated variance-covariance matrix
vcov_matrix <- vcov(neg_model)
cat("\nEstimated variance-covariance matrix:\n")
print(vcov_matrix)
```

```{r}
# Estimated information matrix for beta
info_matrix <- summary(neg_model)$cov.unscaled
cat("\nEstimated information matrix for beta:\n")
print(info_matrix)
```
```{r}
residual_deviance_poisson <- neg_model$deviance
cat("Residual Deviance (Poisson):", residual_deviance_poisson, "\n")

# Degrees of freedom
df_residual_poisson <- neg_model$df.residual
cat("Degrees of Freedom (Residual, Poisson):", df_residual_poisson, "\n")

# Goodness-of-fit test (Chi-squared test)
p_value_poisson <- 1 - pchisq(residual_deviance_poisson, df_residual_poisson)
cat("P-value for Goodness-of-fit test (Poisson):", p_value_poisson, "\n")

# Check significance at 5% level
alpha <- 0.05
if (p_value_poisson < alpha) {
  cat("The Negaitve Binomial model is not adequate based on the Goodness-of-fit test.\n")
} else {
  cat("The Negaive Binomial model is adequate based on the Goodness-of-fit test.\n")
}
```

Question 4
Question 4a)
```{r}
data(birthwt)
```

Question 4b)
```{r}
model_Q4 <- glm(formula = low ~ (smoke +factor(race) + ht + age + ui),family=binomial(link="logit"), data = birthwt)
```

```{r}
summary(model_Q4)
```
```{r}
# Fit the full model including age, lwt, and ui
full_model <- glm(low ~ smoke + factor(race) + ht + age + lwt + ui, family = binomial(link = "logit"), data = birthwt)

# Fit the reduced model excluding age, lwt, and ui
reduced_model <- glm(low ~ smoke + factor(race) + ht, family = binomial(link = "logit"), data = birthwt)

# Likelihood Ratio Test
lr_test <- anova(full_model, reduced_model, test = "Chisq")

# AIC and BIC
aics <- AIC(full_model, reduced_model)
bics <- BIC(full_model, reduced_model)

# Print results
print(lr_test)
summary(full_model)
summary(reduced_model)
```


